urban_project/board/urls.py
from django.urls import path
from . import views
from .views import VoteView

app_name = 'board'

urlpatterns = [
    # path('', views.advertisement_list, name='advertisement_list'),
    path('', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('add/', views.add_advertisement, name='add_advertisement'),
    path('edit/<int:pk>/', views.edit_advertisement, name='edit_advertisement'),
    path('delete/<int:pk>/', views.del_advertisement, name='del_advertisement'),
    path('vote/<int:advertisement_id>/<str:action>/', VoteView.as_view(), name='vote'),


]

urban_project/urban_project/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views as board_views
import debug_toolbar
from urban_project import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('board', include('board.urls', namespace='board')),
                  path('accounts/logout/', board_views.logout_view, name='logout'),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('signup/', board_views.signup, name='signup'),
                  path('stat/', board_views.stat_advertisement, name='stat'),
                  path('', board_views.home, name='home'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

urban_project/board/models.py
from django.db import models
from django.contrib.auth.models import User
from vote.managers import VotableManager
from vote.models import VoteModel




class Advertisement( VoteModel):
    '''
       описание модели таблицы  аdvertisement,
       Подключена библиотека django_vote для оценки рекламмных сообщений
    '''
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='advertisements', null=True, blank=True)
    objects = VotableManager()

    def get_image_path(self):
        return self.image.path

    def get_image_url(self):
        return self.image.url

    def get_image_name(self):
        return self.image.name

    def get_image_full_path(self):
        return self.get_image_path()

    def __str__(self):
        return self.title


class Comment(models.Model):
    '''описание модели таблицы comment'''
    advertisement = models.ForeignKey(Advertisement, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.advertisement}'

class Stat(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    advertisement_count = models.IntegerField(default=0)

    def __str__(self):
        """Возвращает строковое представление профиля пользователя."""
        return self.user.username

urban_project/board/forms.py
from django import forms
from .models import Advertisement
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AdvertisementForm(forms.ModelForm):
    '''Описание формы для ввода данных и передачи их в БД'''

    class Meta:
        model = Advertisement
        fields = ['title', 'content', 'author', 'id', 'image']
        labels = {
            'title': 'Название',
            'content': 'Содержание',
            'author': 'Автор',
            'id': 'номер наверно автора',
            'image' :'фото'
        }


class SignUpForm(UserCreationForm):
    '''Форма регистрации пользователя'''

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)
        labels = {
            'username': 'Имя',
            'password1': 'пароль',
            'password2': 'пароль'
        }


class Tst(forms.Form):
    name = forms.CharField()

urban_project/board/views.py
import os

from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count, Sum, Q
from django.db.models.query import RawQuerySet
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import Advertisement, Stat, Comment
from .forms import AdvertisementForm, Tst
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.views import View
from .signals import *


def logout_view(request):
    logout(request)
    return redirect('home')


from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import login, authenticate


def signup(request):
    ''' Добавление пользовтеля в БД'''
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/board')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def home(request):
    ''' генерация начальной страницы'''
    return render(request, 'home.html')


def advertisement_list(request):
    ''' вывод из БД списа объявлений'''
    # advertisements = Advertisement.objects.all()
    all = Advertisement.votes.count()
    advertisements = Advertisement.objects.all()
    return render(request, 'board/advertisement_list.html', {'advertisements': advertisements}, )


def advertisement_detail(request, pk):
    ''' вывод деталей объявления, номер которого хранится в pk'''
    advertisement = Advertisement.objects.get(pk=pk)
    return render(request, 'board/advertisement_detail.html', {'advertisement': advertisement})


@login_required
def add_advertisement(request):
    ''' добавление объявления'''

    global user_id
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.author = request.user
            if not advertisement.image:
                # Обрабатываем отсутствие файла, ставим заглушку
                advertisement.image = 'advertisements/none.jpg'

            advertisement.save()
            # update_advertisement_count(sender=Advertisement, instance=advertisement, created=True)

            return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm()
    return render(request, 'board/add_advertisement.html', {'form': form})


@login_required
def edit_advertisement(request, pk):
    ''' редактирование переданного обьявления  '''
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES, instance=advertisement)
        if form.is_valid():
            form.instance.author = request.user
            img_obj = form.instance
            form.save()
            return redirect('board:advertisement_detail', pk=img_obj.pk)
    else:
        form = AdvertisementForm(instance=advertisement)
    return render(request, 'board/edit_advertisement.html', {'form': form, 'advertisement': advertisement})


def vote_advertisement(request, post_id):
    ''' функция голосования пользователя и записывает в БД результат'''
    if request.method == 'POST':
        post = get_object_or_404(Advertisement, id=post_id)
        # Проверка, залогинен ли пользователь
        # Голосование
        action = request.POST.get('action')  # 'up' or 'down'
        post.vote(request.user, action)
        post.save()
        return redirect('board/advertisement_list_old.html', pk=post.id)

    return HttpResponseBadRequest()


@login_required
def del_advertisement(request, pk):
    ''' удаление записи, при удалении записис сохраняет файл заглушку'''
    advertisement = get_object_or_404(Advertisement, pk=pk)
    if request.user != advertisement.author:
        return redirect('board:advertisement_list')  # если пользователь не является автором
    if request.method == "POST":

        file_path = advertisement.get_image_full_path()
        file_name = str(advertisement.get_image_name())
        if 'none.jpg' not in file_name:
            advertisement.delete()
            os.remove(file_path)
        else:
            advertisement.delete()

        return redirect('board:advertisement_list')

    return redirect('board:advertisement_detail', pk=pk)

@login_required
def stat_advertisement(request):
    ''' вывод статистики по каждому пользователю в разрезе имя, сколько постов, сколько лайков дизлайков '''
    author_stats = get_author_stats()
    context = {"author_stats": author_stats}
    return render(request, 'stat_advertisement.html', context)

def get_author_stats():
    # # Получаем статистику по каждому автору
    queryset = (Advertisement.objects.values('author_id__username').
                annotate(Count('author_id'), Sum('num_vote_up'), Sum('num_vote_down'),Sum('vote_score') ))

    return list(queryset)





class VoteView(View):
    ''' класс, содержит метод, который отрабатывает голосование и возвращает результат голосования в форму'''

    def post(self, request, advertisement_id, action):
        advertisement = get_object_or_404(Advertisement, pk=advertisement_id)
        if action == 'up':
            advertisement.votes.up(advertisement_id)
        elif action == 'down':
            advertisement.votes.down(advertisement_id)
        else:
            return redirect('board:advertisement_list')
        return redirect('board:advertisement_list')

def advertisement_list(request):
    '''
    Отображение списка объявлений с пагинацией.
    '''
    # Получаем все объявления
    advertisements = Advertisement.objects.all()

    # Пагинация
    paginator = Paginator(advertisements, 5)
    page = request.GET.get('page')

    try:
        # Получаем объявления для текущей страницы
        advertisements_page = paginator.page(page)
    except PageNotAnInteger:
        # Если page не является числом, показываем первую страницу
        advertisements_page = paginator.page(1)
    except EmptyPage:
        # Если page находится за пределами диапазона, показываем последнюю страницу
        advertisements_page = paginator.page(paginator.num_pages)

    return render(request, 'board/1_advertisement_list.html', {
        'advertisements_page': advertisements_page
    })

urban_project/board/templates/board/1_advertisement_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Объявления</h1>

<!-- Кнопка добавления объявления -->
{% if user.is_authenticated %}
<a href="{% url 'board:add_advertisement' %}">
    <button>Добавить объявление</button>
</a>
{% endif %}

<!-- Список объявлений -->
<ul>
    {% for advertisement in advertisements_page %}
    <li>
        <a href="{% url 'board:advertisement_detail' pk=advertisement.pk %}"> ТЕМА обьявления: {{ advertisement.title }}</a>
        <p>  АВТОР: {{advertisement.author}} ! like: {{advertisement.num_vote_up}} dislike {{advertisement.num_vote_down}} <p>
         <div class="vote-buttons" style="display: flex; gap: 10px; align-items: center;">
                <form action="{% url 'board:vote' advertisement.id 'up' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ advertisement.id }}" />
                    <button type="submit" class="btn-like">👍</button>
                </form>
                <form action="{% url 'board:vote' advertisement.id 'down' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ advertisement.id }}" />
                    <button type="submit" class="btn-dislike">👎</button>
                </form>
        </div>
    </li>
    {% endfor %}
</ul>

<!-- Пагинация -->
<div class="pagination">
  <span class="step-links">
    <!-- Предыдущая страница -->
    {% if advertisements_page.has_previous %}
      <a href="?page=1">&laquo; Первая страница</a>
      <a href="?page={{ advertisements_page.previous_page_number }}">Предыдущая страница</a>
    {% endif %}

      <!-- Текущая страница -->
    <span class="current">
      Страница {{ advertisements_page.number }} из {{ advertisements_page.paginator.num_pages }}.
    </span>

      <!-- Следующая страница -->
    {% if advertisements_page.has_next %}
      <a href="?page={{ advertisements_page.next_page_number }}">Следующая страница</a>
      <a href="?page={{ advertisements_page.paginator.num_pages }}">Последняя страница &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock %}

urban_project/board/templates/board/add_advertisement.html
{% extends 'base.html' %}

{% block content %}
<h2>Добавить объявление</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить объявление</button>
</form>
{% endblock %}

urban_project/board/templates/board/advertisement_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Тема: {{ advertisement.title }}</h1>
<h2>Автор: {{ advertisement.author }}</h2>
<p> Содержимое: {{ advertisement.content }}</p>

<style>
        img {
            width: 200px; /* Укажите нужную ширину */
            height: auto; /* Сохраняет пропорции изображения */
        }
    </style>
<h3><img src="{{ advertisement.image.url }}"></h3>

{% if user.is_authenticated %}
    <button onclick="location.href='{% url 'board:edit_advertisement' pk=advertisement.pk %}'">Редактировать</button>
    <form method="post" action="{% url 'board:del_advertisement' pk=advertisement.pk %}" style="display:inline;">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('Вы уверены, что хотите удалитьэту рекламу?');">Удалить</button>
    </form>
{% endif %}
<!--    <a href="{% url 'board:edit_advertisement' advertisement.pk %}">Edit</a>-->

{% endblock %}

urban_project/board/templates/board/advertisement_list.html
{% extends 'base.html' %}
{% load vote %}
{% block content %}

<h1>Объявления</h1>
{% if user.is_authenticated %}
<a href="{% url 'board:add_advertisement' %}">
    <button>Добавить объявление</button>
</a>
{% endif %}

<!-- announcement_list.html -->
<div class="advertisements">
    {% for advertisement in advertisements %}
        <div class="advertisement">
            <!-- Ссылка на редактирование -->
            <a href="{% url 'board:advertisement_detail' pk=advertisement.pk %}" class="advertisement-title">
                ТЕМА обьявления: {{ advertisement.title }} ! АВТОР: {{advertisement.author}} ! like: {{advertisement.num_vote_up}} dislike {{advertisement.num_vote_down}}
            </a>
<div class="vote-buttons" style="display: flex; gap: 10px; align-items: center;">
            <!-- Формы для лайка/дизлайка -->
            <form action="{% url 'board:vote' advertisement.id 'up' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ advertisement.id }}" />
                <button type="submit" class="btn-like">👍</button>
            </form>
            <form action="{% url 'board:vote' advertisement.id 'down' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ advertisement.id }}" />
                <button type="submit" class="btn-dislike">👎</button>
            </form>
        </div>
    {% endfor %}
</div>


<!-- Пагинация -->
<div class="pagination">
  <span class="step-links">
    <!-- Предыдущая страница -->
    {% if advertisements_page.has_previous %}
      <a href="?page=1">&laquo; Первая страница</a>
      <a href="?page={{ advertisements_page.previous_page_number }}">Предыдущая страница</a>
    {% endif %}

      <!-- Текущая страница -->
    <span class="current">
      Страница {{ advertisements_page.number }} из {{ advertisements_page.paginator.num_pages }}.
    </span>

      <!-- Следующая страница -->
    {% if advertisements_page.has_next %}
      <a href="?page={{ advertisements_page.next_page_number }}">Следующая страница</a>
      <a href="?page={{ advertisements_page.paginator.num_pages }}">Последняя страница &raquo;</a>
    {% endif %}
  </span>
</div>

{% endblock %}

urban_project/board/templates/board/edit_advertisement.html
{% extends 'base.html' %}

{% block content %}

<h1>Редактирование объявления</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>

{% endblock %}