urban_project/board/urls.py
from django.urls import path
from . import views
from .views import VoteView

app_name = 'board'

urlpatterns = [
    # path('', views.advertisement_list, name='advertisement_list'),
    path('', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('add/', views.add_advertisement, name='add_advertisement'),
    path('edit/<int:pk>/', views.edit_advertisement, name='edit_advertisement'),
    path('delete/<int:pk>/', views.del_advertisement, name='del_advertisement'),
    path('vote/<int:advertisement_id>/<str:action>/', VoteView.as_view(), name='vote'),


]

urban_project/urban_project/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views as board_views
import debug_toolbar
from urban_project import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('board', include('board.urls', namespace='board')),
                  path('accounts/logout/', board_views.logout_view, name='logout'),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('signup/', board_views.signup, name='signup'),
                  path('stat/', board_views.stat_advertisement, name='stat'),
                  path('', board_views.home, name='home'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

urban_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Django Project{% endblock %}</title>
    <style>
        .navbar {
            overflow: hidden;
            background-color: #333;
            padding: 14px 16px;
        }
        .navbar a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 12px;
            text-decoration: none;
            font-size: 17px;
        }
        .navbar a:hover {
            background-color: #ddd;
            color: black;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'home' %}">Начало</a>
        <a href="{% url 'board:advertisement_list' %}">Доска объявлений</a>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Выйти</a>
            <a href="{% url 'stat' %}">Статистика</a>
        {% else %}
            <a href="{% url 'login' %}">Войти</a>
            <a href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
    </div>

    {% block content %}
    {% endblock %}

</body>
</html>

urban_project/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Домашня страница</title>
</head>
<body>
    <h1>Добро пожаловать на наш сайт!</h1>
    <p><a href="/board/">Go to the board</a></p>
</body>
</html>

urban_project/templates/stat_advertisement.html
{% extends 'base.html' %}

{% block content %}


{% if user.is_authenticated %}

{% for advertisement in author_stats %}
    <h1>
        <br>
            Пользователь = {{ advertisement.author_id__username }}
        </br>
    </h1>
           всего сообщений = {{ advertisement.author_id__count}}
           итого общая сумма откликов  = {{ advertisement.vote_score__sum  }}!
           из них лайк =  {{ advertisement.num_vote_up__sum }}!
           дизлайк  = {{advertisement.num_vote_down__sum  }}!

{% endfor %}

{% endif %}
{% endblock content %}